version:              '4'

services:

  web:
    build:            .
    container_name:   illace-test
    restart:          always
    command:          bash -c "python3 wait_for_postgres.py && python3 manage.py runserver 0.0.0.0:7600"


    volumes:
      - .:/code
    ports:
      - "7600:7600"
    depends_on:
      - db
      - redis
      - fenna-rabbit
    links:
      - redis
      - db
      - fenna-rabbit

  db:
    container_name:   illace-test_db
    image:            vedantbari40/my_postgis:latest
    restart:          always
    volumes:
      - illace-test:/var/lib/postgresql/data/

  redis:
    container_name:   illace-test_redis
    hostname:         redis
    image:            redis:latest
    restart:          always
    volumes:
      - illace-test_redis:/data
    ports:
      - '6379:6379'


  illacetest-worker:
    build:            ./
    restart:          always
    command:          celery -A diceapp.taskapp worker --beat --loglevel=info
    volumes:
      - .:/code
    links:
      - fenna-rabbit
      - redis
    depends_on:
      - web
      - illacetest-rabbit
      - redis

  illacetest-rabbit:
    restart:          always
    hostname:         rabbit-fenna
    image:            rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypassword
      - RABBITMQ_NODE_PORT=5673
    ports:
      - "5676:5673"

volumes:
   illace-test:
     external :       true
   illace-test_redis:
     external:        true
